# WARNING: DON'T use the following secrets in production
apiVersion: v1
kind: Secret
metadata:
  name: rinkeby-geth-nodekey
stringData:
  # address 0x2b3430337f12Ce89EaBC7b0d865F4253c7744c0d
  key: 5df5eff7ef9e4e82739b68a34c6b23608d79ee8daf3b598a01ffb0dd7aa3a2fd
---
apiVersion: ethereum.kotal.io/v1alpha1
kind: Node
metadata:
  name: rinkeby-geth-node
spec:
  network: rinkeby
  client: geth
  nodekeySecretName: rinkeby-geth-nodekey
  rpc: true
  rpcPort: 8599
  corsDomains:
    - example.kotal.io
  rpcAPI:
    - web3
    - net
    - eth
  graphql: true
  graphqlPort: 8777
  resources: &res
    cpu: "1"
    cpuLimit: "1"
    memory: "1Gi"
    memoryLimit: "2Gi"
